spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.initialization-mode=always

spring.data.mongodb.database=secure-software-development
spring.data.mongodb.port=0
spring.data.mongodb.auto-index-creation=true
app.mongodb.seed-enabled=true

spring.ldap.embedded.base-dn=dc=securecar,dc=test
spring.ldap.embedded.ldif=classpath:ldap-data.ldif

app.service-documents.root=service-documents
app.service-documents.safe-bundling=false

server.servlet.session.cookie.http-only=false
server.error.whitelabel.enabled=false
#logging.level.org.springframework.security=DEBUG
